### ISSUE TITLE
Use physical keycodes.

### ISSUE THREAD

**Issue by Sslaxx** [MrEliptik/asteroids#4]
By default the project uses the AZERTY-standard Q and D for left and right. However, as these are not set as physical keycodes (i.e., using the location on the keyboard instead of what the key produces) this means that on other layouts, e.g. QWERTY, the keys are not on the same row. Same goes for the forward and shooting keys.

**Comment by MrEliptik** [comment]
The automatic converter removed the physical keys and turned them into keys! I've fixed it, thanks for letting me know :)
